name: learn-github-actions
on:
  repository_dispatch:
    types: [test-action]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Github Actions テストOK"
        # env:
        #   GITHUB_TOKEN: ${{ secrets.TEST_SECRET }}
